name: benhadley
favicon: null
layout_spectrum: 0
typography_spectrum: 0.35843278001993895
title: Hi My Name Is Ben
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4989d3'
    - '#736a61'
    - '#feffff'
    - '#b2d4fa'
    - '#393220'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
