name: benhadley
favicon: null
layout_spectrum: 0.72538
typography_spectrum: 0.35843278001993895
title: Hi My Name is Ben
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5762358873616904
  lightness: 0.3125
  saturation: 0.17227406683377922
  rhythmicContrast: 0
purpose: []
